CREATE ROLE saver WITH PASSWORD saver;
GRANT CONNECT ON DATABASE repo TO saver;
GRANT ALL ON ALL TABLES IN SCHEMA public TO saver ;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO saver;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO saver;
