name:                hstools-lsp
version:             0.1.0.0
github:              "nboldi91/hstools-lsp"
license:             BSD3
author:              "Boldizsar Nemeth"
maintainer:          "nboldi91@gmail.com"
copyright:           "2022 Boldizsar Nemeth"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nboldi91/hstools-lsp#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Language.Haskell.HsTools.LspServer
    - Language.Haskell.HsTools.LinesDiff
  dependencies:
    - Diff
    - containers
    - split
    - hstools-base
    - lsp >= 1.5
    - lsp-types >= 1.5
    - text
    - lens
    - postgresql-simple
    - bytestring
    - aeson
    - vector
    - mtl
    - time
    - co-log-core

executables:
  hstools-lsp:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hstools-lsp
    - hstools-base

tests:
  hstools-lsp-tests:
    main: AllTests.hs
    source-dirs: tests
    ghc-options:
    - -threaded
    dependencies:
    - hstools-lsp
    - hstools-base
    - base
    - containers
    - HUnit
    - HTF
    - lsp-test
    - lsp-types
    - lsp
    - text
    - process
    - postgresql-simple
    - aeson
    - bytestring
    - time
    - directory
    - filepath

