name:                hstools-base
version:             0.1.0.0
github:              "nboldi91/hstools"
license:             BSD3
author:              "Boldizsar Nemeth"
maintainer:          "nboldi91@gmail.com"
copyright:           "2022 Boldizsar Nemeth"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nboldi91/hstools#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Language.Haskell.HsTools.Database
    - Language.Haskell.HsTools.HandleErrors
    - Language.Haskell.HsTools.LinesDiff
    - Language.Haskell.HsTools.Utils
  dependencies:
    - postgresql-simple
    - time
    - bytestring
    - containers
    - exceptions
    - directory
    - Diff
    - split
    - filepath
  ghc-options:
    - -W
    - -Werror
